import React from 'react';
import {createRoot} from 'react-dom/client';
import {motion} from 'framer-motion';
import {ArrowRight, Check, ChevronDown, Globe2, ShieldCheck, Zap, Menu, X, Play, Sparkles, CreditCard, BarChart3, Code2, LockKeyhole} from 'lucide-react';
import {AreaChart, Area, ResponsiveContainer, Tooltip, XAxis} from 'recharts';
import './style.css';

const chart=[{m:'Jan',v:32},{m:'Feb',v:44},{m:'Mar',v:39},{m:'Apr',v:62},{m:'May',v:57},{m:'Jun',v:81},{m:'Jul',v:76},{m:'Aug',v:96}];
const tx=[['Payment received','Acme Store','+₹2,840.00','Completed'],['Payment received','Nova Digital','+₹1,280.00','Completed'],['Refund issued','Orbit Labs','-₹240.00','Refunded']];
function App(){
 const [menu,setMenu]=React.useState(false);
 return <div className="app">
  <nav className="nav"><div className="brand"><span className="brandMark">P</span><span>pay<span>101</span></span></div><div className="navLinks"><a href="#platform">Platform</a><a href="#solutions">Solutions</a><a href="#developers">Developers</a><a href="#security">Security</a></div><div className="navActions"><button className="ghost">Sign in</button><button className="primary small">Get started <ArrowRight size={15}/></button></div><button className="mobileBtn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></nav>
  {menu&&<div className="mobileMenu"><a href="#platform">Platform</a><a href="#solutions">Solutions</a><a href="#developers">Developers</a><a href="#security">Security</a><button className="primary">Get started</button></div>}
  <main>
   <section className="hero"><div className="orb orb1"/><div className="orb orb2"/><div className="heroCopy"><div className="eyebrow"><span className="pulse"/> Modern payment infrastructure</div><h1>Move money.<br/><em>Move business.</em></h1><p>One powerful platform to accept payments, manage payouts and grow across markets — built for businesses that move fast.</p><div className="heroCtas"><button className="primary">Start accepting payments <ArrowRight size={17}/></button><button className="play"><span><Play size={14} fill="currentColor"/></span> See how it works</button></div><div className="trust"><div className="avatars"><i/><i/><i/><i/></div><span><b>10,000+</b> businesses trust Pay101</span></div></div><Dashboard/></section>
   <section className="logos"><span>BUILT FOR MODERN BUSINESS</span><div><b>acme</b><b>vertex</b><b>northstar</b><b>orbit</b><b>nova</b></div></section>
   <section id="platform" className="section"><div className="sectionHead"><div><span className="kicker">THE PLATFORM</span><h2>Everything you need to <em>get paid.</em></h2></div><p>From your first transaction to your next million, Pay101 gives you the infrastructure to scale without the complexity.</p></div><div className="featureGrid"><Feature icon={<CreditCard/>} title="Accept payments" text="Cards, bank transfers and local methods in one seamless checkout."/><Feature icon={<Zap/>} title="Instant payouts" text="Move funds where they need to go with fast, flexible settlement."/><Feature icon={<Globe2/>} title="Go global" text="Expand into new markets with multi-currency payment flows."/><Feature icon={<ShieldCheck/>} title="Built for trust" text="Security-first controls designed around modern payment risks."/></div></section>
   <section id="solutions" className="split"><div className="splitVisual"><div className="miniCard"><div className="miniTop"><span>PAY101 BALANCE</span><Sparkles size={15}/></div><strong>₹248,920.42</strong><div className="miniChange">↑ 18.6% <small>this month</small></div><div className="miniBars">{[30,52,42,67,54,80,63,91,76,100].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div></div><div className="floatTag tag1"><Check size={15}/> Payment successful</div><div className="floatTag tag2">+ ₹4,820.00</div></div><div className="splitCopy"><span className="kicker">SMARTER OPERATIONS</span><h2>Your payments, <em>in sync.</em></h2><p>See every transaction, settlement and performance signal in one beautifully simple workspace.</p><ul><li><Check/> Real-time transaction visibility</li><li><Check/> Automated reconciliation</li><li><Check/> Powerful reporting & insights</li><li><Check/> Role-based team access</li></ul><button className="textBtn">Explore the platform <ArrowRight size={17}/></button></div></section>
   <section id="developers" className="devSection"><div className="devCopy"><span className="kicker">FOR DEVELOPERS</span><h2>Payments that feel <em>native.</em></h2><p>Simple APIs, clean documentation and webhooks that let your team build payment experiences without fighting the infrastructure.</p><div className="codeTabs"><span>Node.js</span><span>Python</span><span>cURL</span></div><div className="code"><div className="dots"><i/><i/><i/></div><pre><code><span>const</span> payment = <span>await</span> pay101.payments.create({'{'}
  amount: <b>4999</b>,
  currency: <b>'GBP'</b>,
  customer: <b>'cus_101'</b>
{'}'});</code></pre></div></div><div className="apiCard"><Code2 size={24}/><span>API response</span><strong>payment.succeeded</strong><div className="apiRow"><span>id</span><b>pay_8F21A101</b></div><div className="apiRow"><span>amount</span><b>₹49.99</b></div><div className="apiRow"><span>status</span><b className="green">● succeeded</b></div></div></section>
   <section id="security" className="security"><div><span className="kicker">TRUST BY DESIGN</span><h2>Security isn't a feature.<br/><em>It's the foundation.</em></h2></div><div className="securityGrid"><Feature icon={<LockKeyhole/>} title="Secure by default" text="Encryption and access controls throughout the payment lifecycle."/><Feature icon={<ShieldCheck/>} title="Risk intelligence" text="Identify suspicious patterns and protect your payment flows."/><Feature icon={<BarChart3/>} title="Full visibility" text="Actionable insights across payments, customers and markets."/></div></section>
   <section className="cta"><div className="ctaGlow"/><span className="kicker">READY WHEN YOU ARE</span><h2>Build the next chapter<br/>of your <em>payments.</em></h2><p>Start with Pay101 and give your business a payment stack built to scale.</p><button className="primary">Get started with Pay101 <ArrowRight size={17}/></button></section>
  </main><footer><div className="brand"><span className="brandMark">P</span><span>pay<span>101</span></span></div><span>© 2026 Pay101. Demo concept.</span><div><a>Privacy</a><a>Terms</a><a>Contact</a></div></footer>
 </div>
}
function Feature({icon,title,text}){return <motion.div className="feature" whileHover={{y:-5}}><div className="icon">{icon}</div><h3>{title}</h3><p>{text}</p><ArrowRight className="featureArrow" size={17}/></motion.div>}
function Dashboard(){return <motion.div className="dashboard" initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:.8}}><div className="dashGlow"/><div className="dashHead"><div><small>OVERVIEW</small><h3>Good morning, Alex</h3></div><div className="user">A</div></div><div className="stats"><div><span>Total volume</span><strong>₹184,290</strong><b>↑ 24.8%</b></div><div><span>Success rate</span><strong>98.7%</strong><b>↑ 1.2%</b></div></div><div className="chartBox"><div className="chartTitle"><span>Payment volume</span><small>Last 8 months⌄</small></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#79f2c0" stopOpacity=".35"/><stop offset="100%" stopColor="#79f2c0" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="m" hide/><Tooltip contentStyle={{background:'#121b27',border:'1px solid #263747',borderRadius:10}}/><Area type="monotone" dataKey="v" stroke="#79f2c0" strokeWidth={3} fill="url(#fill)"/></AreaChart></ResponsiveContainer></div></div><div className="recent"><span>RECENT ACTIVITY</span>{tx.map((t,i)=><div className="tx" key={i}><div className="txIcon">{i===2?'↗':'₹'}</div><div><b>{t[0]}</b><small>{t[1]}</small></div><strong className={i===2?'minus':''}>{t[2]}</strong><i>{t[3]}</i></div>)}</div></motion.div>}
createRoot(document.getElementById('root')).render(<App/>);
